name = "woldecks-board"
main = "worker/index.js"
compatibility_date = "2026-02-01"

[vars]
SUPABASE_URL = "https://vkhigtmnmylooczzwzhl.supabase.co"
ALLOWED_ORIGIN = "https://woldecks-board.pages.dev,https://84fb1e13.woldecks-board.pages.dev"
